version: '3'

services:
  python_service:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        - BASE_IMAGE=python:3.9
        - APP_VERSION=2.0

    environment:
      - DEBUG=true

    image: nasim1039/python_web:2.0

  node_service:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        - BASE_IMAGE=node:21
        - APP_NAME=my-nodejs-app

    environment:
      - NODE_ENV=Development
    image: nasim1039/node_web:2.0

  