version: '3'
services:
  web:
   #Pull the Image from Repository.
   image: nasim1039/web:0.1
 # Command used to deploy the Service

   deploy:
     replicas: 5
     resources:
       limits:
         cpus: "0.1"
         memory: 50M
     restart_policy:
      condition: on-failure

   ports:
     - "4000:80"

   networks:
      - webnet


  redis:
   image: redis:latest
   ports:
     - "6379:6379"
   volumes:
     - "app/redis_data:/data"
   deploy:
     placement:
       constraints: [node.hostname == manager2]
   command: redis-server --appendonly yes
   networks:
    - webnet
networks:
  webnet:
         