version: '3'

services:
  #MYSQL Service as database
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always

    environment:
      - "MYSQL_ROOT_PASSWORD: mysqlroot"
      - "MYSQL_DATABASE: wordpress"
      - "MYSQL_USER: wordpressuser"
      - "MYSQL_PASSWORD: wordpresspass"
      
    volumes:
      - mysql-db:/var/lib/mysql

    networks:
      - wordpress-network
    
    ports:
      - "3306:3306"

  wordpress:
    #Wordpress for Frontend Application
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-container
    restart: always

    environment:
      - "WORDPRESS_DB_HOST: db:3306"
      - "WORDPRESS_DB_USER: wordpressuser"
      - "WORDPRESS_PASSWORD: wordpresspass"
      - "WORDPRESS_DB_NAME: wordpress"

    
    volumes:
      - wordpress-vol:/var/www/html

    ports:
      - "8080:80"
    
    networks:
      - wordpress-network

volumes:
  mysql-db:
  wordpress-vol:

networks:
  wordpress-network:
    driver: bridge
