version: "3.1"
services:
  postgressDB:
    image: postgress:latest
    secrets:
      - db_username
      - db_password
    environment:
      - POSTGRESS_USER-FILE:/run/secret/db_password
      - POSTGRESS_PASSWORD-FILE:/run/secret/db_username

  centos:
    image: centos
    deploy:
      replicas: 2
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    secrets:
      - my-secret

secrets:
  db_password: 
   file: ./postgress_db_password.txt
  db_username:
    file: ./postgress_username.txt
  
  my-secret:
   external: true
     

        